### ISSUE TITLE
File is not renamed to *.html

### ISSUE THREAD

**Issue by vishuml** [leo-buneev/pug-to-html#1]
Hey :)

So the issue is that the file is not renamed from *.pug to *.html.
The code is converted from pug to html but I get an error 

`(node:17682) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
 ›   Error: ERROR while processing [PATH]/filename.pug`

and then the process ends with *.pug file but html inside.

**Comment by vishuml** [comment]
You need to add parameter with old file name in fs.rename

**Comment by leo-buneev** [comment]
Resolved. Thx @vishuml
